[conf]
default-lang = "en"

[lang.en]
resume = "Résumé"
dear = "Dear"
letter = "Letter"
attached = "Attached"
curriculum-vitae = "Curriculum Vitae"
sincerely = "Sincerely"
subject = "Subject:"

[lang.de]
resume = "Lebenslauf"
dear = "Sehr geehrte/r"
letter = "Brief"
attached = "Anlage"
curriculum-vitae = "Lebenslauf"
sincerely = "Mit freundlichen Grüßen"
subject = "Betreff:"

[lang.gr]
resume = "Βιογραφικό"
dear = "Αγαπητέ/Αγαπητή"
letter = "Επιστολή"
attached = "Συνημμένα"
curriculum-vitae = "Βιογραφικό"
sincerely = "Με εκτίμηση"
subject = "Θέμα:"

[lang.pt]
resume = "Currículo"
dear = "Caro/Cara"
letter = "Carta"
attached = "Anexo"
curriculum-vitae = "Currículo"
sincerely = "Atenciosamente"
subject = "Assunto:"

[lang.sp]
resume = "Currículum"
dear = "Estimado/Estimada"
letter = "Carta"
attached = "Adjunto"
curriculum-vitae = "Currículum"
sincerely = "Atentamente"
subject = "Asunto:"

[lang.fr]
resume = "Curriculum Vitae"
dear = "Madame, Monsieur"
letter = "Lettre"
attached = "Pièce jointe"
curriculum-vitae = "Curriculum Vitae"
sincerely = "Cordialement"
subject = "Objet :"

[lang.ru]
resume = "Резюме"
dear = "Уважаемый/Уважаемая"
letter = "Письмо"
attached = "Приложение"
curriculum-vitae = "Биографическая справка"
sincerely = "С уважением"
subject = "Тема:"

[lang.zh]
resume = "简历"
dear = "尊敬的"
letter = "信件"
attached = "附件"
curriculum-vitae = "简历"
sincerely = "此致敬礼"
subject = "主题："

[lang.it]
resume = "Curriculum Vitae"
dear = "Egregio/Egregia"
letter = "Lettera"
attached = "Allegato"
curriculum-vitae = "Curriculum Vitae"
sincerely = "Distinti saluti"
subject = "Oggetto:"
